const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Date,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Date.Exps.GetUTCSeconds,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Date.Exps.GetDate,
		C3.Plugins.Date.Exps.GetMonth,
		C3.Plugins.Date.Exps.GetYear,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.System.Exps.regexreplace,
		C3.Plugins.System.Cnds.RegexTest,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Browser.Acts.RequestFullScreen
	];
};
self.C3_JsPropNameTable = [
	{collisionCount1: 0},
	{collisionCount2: 0},
	{collisionCount3: 0},
	{Asset: 0},
	{Asset10: 0},
	{Asset11: 0},
	{Asset12: 0},
	{Asset13: 0},
	{Asset14: 0},
	{Asset15: 0},
	{Asset16: 0},
	{Asset17: 0},
	{Asset18: 0},
	{Asset19: 0},
	{Asset2: 0},
	{Asset20: 0},
	{Asset3: 0},
	{Asset4: 0},
	{Asset5: 0},
	{Asset6: 0},
	{Rotate: 0},
	{Asset7: 0},
	{Asset8: 0},
	{Pin: 0},
	{Asset9: 0},
	{Particles: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Pos: 0},
	{Lose: 0},
	{Santa_: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Tween: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Asset21: 0},
	{Screenshottt: 0},
	{Touch: 0},
	{Score: 0},
	{Text: 0},
	{ScoreText: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Text_min: 0},
	{Date: 0},
	{Text_sec: 0},
	{Text_min2: 0},
	{Text_counttime: 0},
	{Text_currentime: 0},
	{Text_Date: 0},
	{Text_Discount1: 0},
	{Text_Discount2: 0},
	{AmanDua: 0},
	{Text_Discount3: 0},
	{Button_Back: 0},
	{Browser: 0},
	{shared0sheet: 0},
	{Text3: 0},
	{Text_min3: 0},
	{Text_min4: 0},
	{Green1: 0},
	{GreenCount1: 0},
	{Green2: 0},
	{GreenCount2: 0},
	{Green3: 0},
	{GreenCount3: 0},
	{Green4: 0},
	{GreenCount4: 0},
	{Red1: 0},
	{RedCount1: 0},
	{Red2: 0},
	{RedCount2: 0},
	{Red3: 0},
	{RedCount3: 0},
	{Red4: 0},
	{RedCount4: 0},
	{DrPiyush: 0},
	{Dr: 0},
	{AJAX: 0},
	{JSON: 0},
	{TextInput: 0},
	{Email_Id: 0},
	{Name: 0},
	{Phone: 0},
	{Submit: 0},
	{StarID: 0},
	{Star: 0},
	{Text2: 0},
	{Text4: 0},
	{Submit_2: 0},
	{Submit_user: 0},
	{BG: 0},
	{ThankYou: 0},
	{Rate: 0},
	{RateUs: 0},
	{Text6: 0},
	{Button3: 0},
	{Bar_2: 0},
	{Sine: 0},
	{DermaQuest_Splash: 0},
	{Bar_: 0},
	{Bar_3: 0},
	{TextInput2: 0},
	{TFamily: 0},
	{currentTime: 0},
	{Email: 0},
	{UserName: 0},
	{PhoneNumber: 0},
	{PlayerId: 0},
	{MongoId: 0},
	{showCountdown: 0},
	{SelectedRating: 0},
	{countdownTime: 0},
	{Form: 0},
	{Hap: 0},
	{Best: 0},
	{MUTE: 0},
	{Submitbtn: 0},
	{Discount: 0}
];

self.InstanceType = {
	Asset: class extends self.ISpriteInstance {},
	Asset10: class extends self.ISpriteInstance {},
	Asset11: class extends self.ISpriteInstance {},
	Asset12: class extends self.ISpriteInstance {},
	Asset13: class extends self.ISpriteInstance {},
	Asset14: class extends self.ISpriteInstance {},
	Asset15: class extends self.ISpriteInstance {},
	Asset16: class extends self.ISpriteInstance {},
	Asset17: class extends self.ISpriteInstance {},
	Asset18: class extends self.ISpriteInstance {},
	Asset19: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Asset20: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	Asset4: class extends self.ISpriteInstance {},
	Asset5: class extends self.ISpriteInstance {},
	Asset6: class extends self.ISpriteInstance {},
	Asset7: class extends self.ISpriteInstance {},
	Asset8: class extends self.ISpriteInstance {},
	Asset9: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Santa_: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Asset21: class extends self.ISpriteInstance {},
	Screenshottt: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	ScoreText: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Text_min: class extends self.ITextInstance {},
	Date: class extends self.IInstance {},
	Text_sec: class extends self.ITextInstance {},
	Text_min2: class extends self.ITextInstance {},
	Text_counttime: class extends self.ITextInstance {},
	Text_currentime: class extends self.ITextInstance {},
	Text_Date: class extends self.ITextInstance {},
	Text_Discount1: class extends self.ITextInstance {},
	Text_Discount2: class extends self.ITextInstance {},
	AmanDua: class extends self.ISpriteInstance {},
	Text_Discount3: class extends self.ITextInstance {},
	Button_Back: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	shared0sheet: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text_min3: class extends self.ITextInstance {},
	Text_min4: class extends self.ITextInstance {},
	GreenCount1: class extends self.ITextInstance {},
	GreenCount2: class extends self.ITextInstance {},
	GreenCount3: class extends self.ITextInstance {},
	GreenCount4: class extends self.ITextInstance {},
	RedCount1: class extends self.ITextInstance {},
	RedCount2: class extends self.ITextInstance {},
	RedCount3: class extends self.ITextInstance {},
	RedCount4: class extends self.ITextInstance {},
	DrPiyush: class extends self.ITextInstance {},
	Dr: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Email_Id: class extends self.ITextInputInstance {},
	Name: class extends self.ITextInputInstance {},
	Phone: class extends self.ITextInputInstance {},
	Submit: class extends self.IButtonInstance {},
	Star: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Submit_2: class extends self.ISpriteInstance {},
	Submit_user: class extends self.ITextInstance {},
	BG: class extends self.ISpriteInstance {},
	ThankYou: class extends self.ITextInstance {},
	Rate: class extends self.ISpriteInstance {},
	RateUs: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Button3: class extends self.IButtonInstance {},
	Bar_2: class extends self.ISpriteInstance {},
	DermaQuest_Splash: class extends self.ISpriteInstance {},
	Bar_: class extends self.ISpriteInstance {},
	Bar_3: class extends self.ISpriteInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	TFamily: class extends self.ISpriteInstance {}
}